spring:
  datasource:
    url: ${DB_URL_Qa}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME_Qa}
    password: ${DB_PASSWORD_Qa}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect