spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ridepilot
    username: postgres
    password: 2024
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  doc:
    api-docs:
      path: /v1/api-docs
    swagger-ui:
      path: /swagger-ui.html
